branch-defaults:
  default:
    environment: KeylockerBackend-env
environment-defaults:
  KeylockerBackend-env-1:
    branch: null
    repository: null
global:
  application_name: KeylockerBackend
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
